[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }
file-types = ["c", "h"]

[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "    " }
file-types = ["cpp", "hpp"]

[[language]]
name = "rust"
auto-format = true

